obs:
  address: "localhost"
  port: 4444
  password: null

vts:
  address: "localhost"
  port: 8001

scenes_to_hotkeys:
  "Scene": "My Animation 1"
  "Scene 2": "My Animation 2"
  "Scene 3": "My Animation 3"

# Hotkey to trigger when no scene match is found
# Set to null to disable changing the animation in that case
# Not recommended, it's best to have a default animation
default_hotkey: "My Animation 1"
# default_hotkey: null

# Delay in milliseconds before triggering the hotkey after a scene change
# Useful if you want to hide the transition behind an intermission video for
# example
# Set to 0 to disable any delay
transition_delay_ms: 5000

# Set to true to wait half of the transition delay before triggering the hotkey
# This bypasses the transition_delay_ms setting entirely
transition_delay_half: false
